### ISSUE TITLE
How to run existing fcn8 model file

### ISSUE THREAD

**Issue by sreevasu** [pecarlat/caffeTools#2]
HI pecarlat,

can you suggest me, i want to use existing fcn8 model file and test the segmentation  results. How can i do. please can you send any code related to this. 

Thanking you

**Comment by pierre-ecarlat** [comment]
Hi,
I used this code: https://github.com/pecarlat/caffe/blob/master/caffeTools/runSegmentation.py
But this question is not an issue nor a feature suggestion, so it has nothing to do here. Next time, use stackoverflow community instead.
Pierre

**Comment by sreevasu** [comment]
HI pecarlat,

Thank you very much for your help.
